const storyTitleData = [
  {
    id: 1,
    arcTitle:"Stories from the Eastern Fief",
    storyOneTitle: "Soon-to-be-Title Soon-to-be-Title Soon-to-be-Title Soon-to-be-Title Soon-to-be-Title",
    storyOneLink: "storyonetitle",
    storyTwoTitle: "Soon-to-be-Title",
    storyTwoLink: "storytwotitle",
    storyThreeTitle: undefined,
    storyThreeLink: "storythreetitle",
    storyFourTitle: undefined,
    storyFourLink: "storyfourtitle",
    storyFiveTitle: undefined,
    storyFiveLink: "storyfivetitle",
  },
  {
    id: 2,
    arcTitle:"Western Issues",
    storyOneTitle: "Soon-to-be-Title",
    storyOneLink: "storyonetitle",
    storyTwoTitle: "Soon-to-be-Title",
    storyTwoLink: "storytwotitle",
    storyThreeTitle: undefined,
    storyThreeLink: "storythreetitle",
    storyFourTitle: undefined,
    storyFourLink: "storyfourtitle",
    storyFiveTitle: undefined,
    storyFiveLink: "storyfivetitle",
  },
  {
    id: 3,
    arcTitle:"Stories from the Eastern Fief",
    storyOneLink: "storyonetitle",
    storyTwoTitle: "Soon-to-be-Title",
    storyTwoLink: "storytwotitle",
    storyThreeTitle: undefined,
    storyThreeLink: "storythreetitle",
    storyFourTitle: undefined,
    storyFourLink: "storyfourtitle",
    storyFiveTitle: undefined,
    storyFiveLink: "storyfivetitle",
  },
  {
    id: 4,
    arcTitle:"Western Issues",
    storyOneLink: "storyonetitle",
    storyTwoTitle: "Soon-to-be-Title",
    storyTwoLink: "storytwotitle",
    storyThreeTitle: undefined,
    storyThreeLink: "storythreetitle",
    storyFourTitle: undefined,
    storyFourLink: "storyfourtitle",
    storyFiveTitle: undefined,
    storyFiveLink: "storyfivetitle",
  }
];

export default storyTitleData;